spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/datanuri_board
    username: postgres
    password: 1111
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  profiles:
    include: oauth
jwt:
  secret: dGVzdGRhdGFudXJpdGVzdGRhdGFudXJpdGVzdGRhdGFudXJpdGVzdGRhdGFudXJpdGVzdGRhdGFudXJpIHRlc3RkYXRhbnVyaXRlc3RkYXRhbnVyaXRlc3RkYXRhbnVyaXRlc3RkYXRhbnVyaXRlc3RkYXRhbnVyaQ